// Top-level build file (minimal). Versions & repositories managed in settings.gradle.

apply from: "variables.gradle"

subprojects { p ->
    plugins.withId("com.android.application") {
        p.android {
            compileOptions {
                sourceCompatibility = JavaVersion.VERSION_21
                targetCompatibility = JavaVersion.VERSION_21
            }
        }
    }
    plugins.withId("com.android.library") {
        p.android {
            compileOptions {
                sourceCompatibility = JavaVersion.VERSION_21
                targetCompatibility = JavaVersion.VERSION_21
            }
        }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
